# 2.3 SOO for 2D vector field

We load the necessary objects.

In [1]:
import numpy as np

from cyclops.object_reader import PickleManager
from cyclops.plotting import PlotManager
from cyclops.sim_reader import MeshReader

# Load any objects necessary
reader = MeshReader("data/monoblock_out.e")
pickle_manager = PickleManager()
graph_manager = PlotManager()

# Read the simulation data
sensor_region = "right"
pos_3D = reader.read_pos(sensor_region)
grid = reader.generate_grid(5)

# Get the min and max bounds along each axis (x, y, z)
min_bounds = np.min(grid, axis=0)
max_bounds = np.max(grid, axis=0)
bounds = np.vstack((min_bounds, max_bounds))

disp = np.array(
    [
        reader.read_scalar(sensor_region, "disp_x"),
        reader.read_scalar(sensor_region, "disp_y"),
        reader.read_scalar(sensor_region, "disp_z"),
    ]
).T
print(disp[0])

[ 5.42377424e-05  3.28911344e-05 -2.36492004e-05]


We setup the sensor suite

In [2]:
from cyclops.fields import VectorField
from cyclops.regressors import RBFModel
from cyclops.sensor_suite import SensorSuite
from cyclops.sensors import PointSensor
import numpy as np


# Setup the sensor suite
def f(x):
    return np.zeros(x.shape)

centre_point=np.array([[-5e10, -5e10, -5e10], [5e10, 5e10, 5e10]])

sensor = PointSensor(field_dim=2, offset_function= callable, centre_point=centre_point)
sensors = np.array([sensor] * 5)

disp_field = VectorField(RBFModel, bounds)
disp_field.fit_model(pos_3D, disp)
print(disp_field._regression_type)

field_bounds = disp_field.get_bounds()
sensor_bounds = field_bounds + np.array([[1, 1, 1], [-1, -1, -1]]) * 0.002



sensor_suite = SensorSuite(
    disp_field,
    sensors, sensor_pos=centre_point, field_points=pos_3D, field_vec=disp
)

print(sensor_suite.predict_data(comparison_pos=[[-4e10, -4e10, -4e10], [4e10, 4e10, 4e10]]))

<class 'cyclops.regressors.RBFModel'>
[[[ 1.89901963e+19  2.19804635e+19 -2.23589148e+18]
  [-1.89901963e+19 -2.19804635e+19  2.23589148e+18]]]


We setup the optimisation.

In [ ]:
from cyclops.experiment import Experiment
from cyclops.optimisers import PSOOptimiser

# Setup the experiment
optimiser = PSOOptimiser("00:00:10")
experiment = Experiment(
    true_temp_field,
    grid,
    optimiser,
)
experiment.plan_soo(
    sensor_suite,
    sensor_bounds,
)
res = experiment.design()
(
    proposed_layout,
    true_disps,
    model_disps,
    sensor_vals,
) = experiment.get_SOO_plotting_arrays(res.X)

We plot the mangitudes of the fields to compare.

In [ ]:
mag_true_disps = np.linalg.norm(true_disps, axis=1).reshape(-1, 1)
mag_model_disps = np.linalg.norm(model_disps, axis=1).reshape(-1, 1)
mag_sensor_vals = np.linalg.norm(sensor_vals, axis=1).reshape(-1, 1)

# Display the results
graph_manager.build_optimisation(res.history)
graph_manager.draw()
graph_manager.build_2D_compare(grid, proposed_layout, mag_true_disps, mag_model_disps)
graph_manager.draw()
graph_manager.build_3D_compare(grid, mag_true_disps, mag_model_disps)
graph_manager.draw()